### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by TheAnnoyingFruit** [SabeMP/taR#3]
I don't know if it is that your instructions on how to use it are unclear or user error but trying to open RatataR does nothing. Putting it in the games root folder and trying to run it also do nothing.

**Comment by SplasBoi** [comment]
Hey. Sorry for having issues with RatataR.
Here are some things you can try:

1. Ensure that your antivirus software is not blocking RatataR. Try adding an exception for RatataR.exe and hook.dll or the game folder.

2. Confirm that you are using the USA game version, which exclusively features English text and audio. To verify this, generate md5 hash for overlay.exe, and compare it to this: 9948615D068513BAB955DE0CBADF00C2.

3. Other modifications made to the game can interfere with RatataR. Consider reinstalling the game to get a clean installation.

**Comment by TheAnnoyingFruit** [comment]
1. I do not have any antivirus active to block the application
2. I do not know if I have done something wrong or have a wildly different version but the hash I get is 4b7d8913595a2fe1f1dfee6538f47ac8.
3. I have reinstalled the game clean a few times now.

**Comment by SplasBoi** [comment]
The hash indicates that your game is from the action pack bundle. That version is currently not supported. Multi-version support is planned to be implemented but I cannot guarantee it will happen anytime soon.

Sorry for the inconvenience.

**Comment by TheAnnoyingFruit** [comment]
That was it thank you. I got a copy of that version and everything is working now

**Comment by TheAnnoyingFruit** [comment]
Also maybe you could add a note to the read me. That says that this works on steam deck since I have tested it there and have had no issues.
