### ISSUE TITLE
Compatibility with the European version?

### ISSUE THREAD

**Issue by Lusiiky** [SabeMP/taR#4]
Hello,

I'd just like to know if it would be possible to make RatataR compatible with the European version?

OR if you could tell me if it's easy to apply RatataR's improvements to the game manually?

Thanks a lot!
Lusiiky

**Comment by SplasBoi** [comment]
Hey. There is not just one single European version.
What in game languages does you game have? If I have your specific version, I'll make a custom patch that works for yours.

**Comment by Lusiiky** [comment]
> Hey. There is not just one single European version. What in game languages does you game have? If I have your specific version, I'll make a custom patch that works for yours.

Hello @SplasBoi ,

Oh yes, sorry, I don't know the different versions that exist.

I have the version with the French language (which I use) and Dutch.

If you need it, I can always provide you with the necessary files.

Thank you!
Lusiiky

**Comment by SplasBoi** [comment]
I conveniently already have a patch for that version. Try replacing the hook.dll with this one:
[dutchPatch.zip](https://github.com/user-attachments/files/17435580/dutchPatch.zip)

**Comment by Lusiiky** [comment]
All I get is a ‘Disc reading failed’, even though I've moved MUSIC and VIDEO into Ratatouille D:

**Comment by SplasBoi** [comment]
Make sure to copy the music and videos folder into the Rat folder where overlay.exe is

**Comment by Lusiiky** [comment]
> Make sure to copy the music and videos folder into the Rat folder where overlay.exe is

Oh! You wrote ‘Copy the “MUSIC” and “VIDEOS” folders into your Ratatouille game folder.’, so I thought it was literally in the ‘Ratatouille’ folder, not the Rat folder.
Thanks for this!

**Comment by SplasBoi** [comment]
My bad. I should have made that clearer. Glad I could help!
